export const constants = {
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  SENDGRID_FROM: process.env.SENDGRID_FROM,
  VERIFY_TEMPLATE_ID: process.env.VERIFY_TEMPLATE_ID,
  WELCOME_TEMPLATE_ID: process.env.WELCOME_TEMPLATE_ID,
  FORGET_TEMPLATE_ID: process.env.FORGET_TEMPLATE_ID,
  PACKAGE_PURCHASE_ID: process.env.PACKAGE_PURCHASE_ID,
  ORDER_APPROVAL: process.env.ORDER_APPROVAL,
  ORDER_REJECTED: process.env.ORDER_REJECTED,
  INGREDIENT_LIST: process.env.INGREDIENT_LIST,
  LINE_MEETING_TEMPLATE_ID: process.env.LINE_MEETING_TEMPLATE_ID,
  JOIN_NOW_TEMPLATE_ID: process.env.JOIN_NOW_TEMPLATE_ID,
};
