export const constants = {
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_PUBLISH_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
  SESSION_SECRET: process.env.SESSION_SECRET,
  STRIPE_CONNECT_PLATFORM_CLIENT_ID:
    process.env.STRIPE_CONNECT_PLATFORM_CLIENT_ID,
  STRIPE_CONNECT_PLATFORM_AUTHORIZE_URI:
    process.env.STRIPE_CONNECT_PLATFORM_AUTHORIZE_URI,
  STRIPE_CONNECT_PLATFORM_AUTHORIZE_TOKEN_URI:
    process.env.STRIPE_CONNECT_PLATFORM_AUTHORIZE_TOKEN_URI,
  ACCOUNT_TYPE: process.env.ACCOUNT_TYPE,
  BUSINESS_TYPE: process.env.BUSINESS_TYPE,
  WEBHOOK_CHARGE_SECRET_KEY: process.env.WEBHOOK_CHARGE_SECRET_KEY,
  PAYMENT_METHODS: process.env.PAYMENT_METHODS.split(', '),
  ALLOWED_COUNTRIES: process.env.ALLOWED_COUNTRIES.split(', '),
  MODE: process.env.MODE,
  APPLICATION_FEE: process.env.APPLICATION_FEE,
  CHECKOUT_SUCCESS_URL: process.env.CHECKOUT_SUCCESS_URL,
  CHECKOUT_CANCEL_URL: process.env.CHECKOUT_CANCEL_URL,
};
